//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioArticuloReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulo", Namespace="http://tempuri.org/")]
    public partial class Articulo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string CodigoField;
        
        private string NombreField;
        
        private string CategoriaField;
        
        private decimal PreciocompraField;
        
        private decimal PrecioventaField;
        
        private int StockField;
        
        private string ProveedorField;
        
        private System.Nullable<int> StockminimoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodigoField, value) != true))
                {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NombreField, value) != true))
                {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true))
                {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Preciocompra
        {
            get
            {
                return this.PreciocompraField;
            }
            set
            {
                if ((this.PreciocompraField.Equals(value) != true))
                {
                    this.PreciocompraField = value;
                    this.RaisePropertyChanged("Preciocompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Precioventa
        {
            get
            {
                return this.PrecioventaField;
            }
            set
            {
                if ((this.PrecioventaField.Equals(value) != true))
                {
                    this.PrecioventaField = value;
                    this.RaisePropertyChanged("Precioventa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                if ((this.StockField.Equals(value) != true))
                {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Proveedor
        {
            get
            {
                return this.ProveedorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true))
                {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> Stockminimo
        {
            get
            {
                return this.StockminimoField;
            }
            set
            {
                if ((this.StockminimoField.Equals(value) != true))
                {
                    this.StockminimoField = value;
                    this.RaisePropertyChanged("Stockminimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticuloRegistrarResult", Namespace="http://tempuri.org/")]
    public partial class ArticuloRegistrarResult : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioArticuloReference.IServicioArticulos")]
    public interface IServicioArticulos
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento articulo del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArticulos/InsertarArticuloSoap", ReplyAction="*")]
        ServicioArticuloReference.InsertarArticuloSoapResponse InsertarArticuloSoap(ServicioArticuloReference.InsertarArticuloSoapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArticulos/InsertarArticuloSoap", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioArticuloReference.InsertarArticuloSoapResponse> InsertarArticuloSoapAsync(ServicioArticuloReference.InsertarArticuloSoapRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigo del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArticulos/ConsultarArticuloPorCodigoSoap", ReplyAction="*")]
        ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponse ConsultarArticuloPorCodigoSoap(ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArticulos/ConsultarArticuloPorCodigoSoap", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponse> ConsultarArticuloPorCodigoSoapAsync(ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarArticuloSoapRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarArticuloSoap", Namespace="http://tempuri.org/", Order=0)]
        public ServicioArticuloReference.InsertarArticuloSoapRequestBody Body;
        
        public InsertarArticuloSoapRequest()
        {
        }
        
        public InsertarArticuloSoapRequest(ServicioArticuloReference.InsertarArticuloSoapRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarArticuloSoapRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioArticuloReference.Articulo articulo;
        
        public InsertarArticuloSoapRequestBody()
        {
        }
        
        public InsertarArticuloSoapRequestBody(ServicioArticuloReference.Articulo articulo)
        {
            this.articulo = articulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarArticuloSoapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarArticuloSoapResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioArticuloReference.InsertarArticuloSoapResponseBody Body;
        
        public InsertarArticuloSoapResponse()
        {
        }
        
        public InsertarArticuloSoapResponse(ServicioArticuloReference.InsertarArticuloSoapResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarArticuloSoapResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioArticuloReference.ArticuloRegistrarResult InsertarArticuloSoapResult;
        
        public InsertarArticuloSoapResponseBody()
        {
        }
        
        public InsertarArticuloSoapResponseBody(ServicioArticuloReference.ArticuloRegistrarResult InsertarArticuloSoapResult)
        {
            this.InsertarArticuloSoapResult = InsertarArticuloSoapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarArticuloPorCodigoSoapRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarArticuloPorCodigoSoap", Namespace="http://tempuri.org/", Order=0)]
        public ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequestBody Body;
        
        public ConsultarArticuloPorCodigoSoapRequest()
        {
        }
        
        public ConsultarArticuloPorCodigoSoapRequest(ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarArticuloPorCodigoSoapRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public ConsultarArticuloPorCodigoSoapRequestBody()
        {
        }
        
        public ConsultarArticuloPorCodigoSoapRequestBody(string codigo)
        {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarArticuloPorCodigoSoapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarArticuloPorCodigoSoapResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponseBody Body;
        
        public ConsultarArticuloPorCodigoSoapResponse()
        {
        }
        
        public ConsultarArticuloPorCodigoSoapResponse(ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarArticuloPorCodigoSoapResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioArticuloReference.Articulo ConsultarArticuloPorCodigoSoapResult;
        
        public ConsultarArticuloPorCodigoSoapResponseBody()
        {
        }
        
        public ConsultarArticuloPorCodigoSoapResponseBody(ServicioArticuloReference.Articulo ConsultarArticuloPorCodigoSoapResult)
        {
            this.ConsultarArticuloPorCodigoSoapResult = ConsultarArticuloPorCodigoSoapResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioArticulosChannel : ServicioArticuloReference.IServicioArticulos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioArticulosClient : System.ServiceModel.ClientBase<ServicioArticuloReference.IServicioArticulos>, ServicioArticuloReference.IServicioArticulos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioArticulosClient() : 
                base(ServicioArticulosClient.GetDefaultBinding(), ServicioArticulosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioArticulos_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioArticulosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioArticulosClient.GetBindingForEndpoint(endpointConfiguration), ServicioArticulosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioArticulosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioArticulosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioArticulosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioArticulosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioArticulosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioArticuloReference.InsertarArticuloSoapResponse ServicioArticuloReference.IServicioArticulos.InsertarArticuloSoap(ServicioArticuloReference.InsertarArticuloSoapRequest request)
        {
            return base.Channel.InsertarArticuloSoap(request);
        }
        
        public ServicioArticuloReference.ArticuloRegistrarResult InsertarArticuloSoap(ServicioArticuloReference.Articulo articulo)
        {
            ServicioArticuloReference.InsertarArticuloSoapRequest inValue = new ServicioArticuloReference.InsertarArticuloSoapRequest();
            inValue.Body = new ServicioArticuloReference.InsertarArticuloSoapRequestBody();
            inValue.Body.articulo = articulo;
            ServicioArticuloReference.InsertarArticuloSoapResponse retVal = ((ServicioArticuloReference.IServicioArticulos)(this)).InsertarArticuloSoap(inValue);
            return retVal.Body.InsertarArticuloSoapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioArticuloReference.InsertarArticuloSoapResponse> ServicioArticuloReference.IServicioArticulos.InsertarArticuloSoapAsync(ServicioArticuloReference.InsertarArticuloSoapRequest request)
        {
            return base.Channel.InsertarArticuloSoapAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioArticuloReference.InsertarArticuloSoapResponse> InsertarArticuloSoapAsync(ServicioArticuloReference.Articulo articulo)
        {
            ServicioArticuloReference.InsertarArticuloSoapRequest inValue = new ServicioArticuloReference.InsertarArticuloSoapRequest();
            inValue.Body = new ServicioArticuloReference.InsertarArticuloSoapRequestBody();
            inValue.Body.articulo = articulo;
            return ((ServicioArticuloReference.IServicioArticulos)(this)).InsertarArticuloSoapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponse ServicioArticuloReference.IServicioArticulos.ConsultarArticuloPorCodigoSoap(ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest request)
        {
            return base.Channel.ConsultarArticuloPorCodigoSoap(request);
        }
        
        public ServicioArticuloReference.Articulo ConsultarArticuloPorCodigoSoap(string codigo)
        {
            ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest inValue = new ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest();
            inValue.Body = new ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequestBody();
            inValue.Body.codigo = codigo;
            ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponse retVal = ((ServicioArticuloReference.IServicioArticulos)(this)).ConsultarArticuloPorCodigoSoap(inValue);
            return retVal.Body.ConsultarArticuloPorCodigoSoapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponse> ServicioArticuloReference.IServicioArticulos.ConsultarArticuloPorCodigoSoapAsync(ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest request)
        {
            return base.Channel.ConsultarArticuloPorCodigoSoapAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioArticuloReference.ConsultarArticuloPorCodigoSoapResponse> ConsultarArticuloPorCodigoSoapAsync(string codigo)
        {
            ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest inValue = new ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequest();
            inValue.Body = new ServicioArticuloReference.ConsultarArticuloPorCodigoSoapRequestBody();
            inValue.Body.codigo = codigo;
            return ((ServicioArticuloReference.IServicioArticulos)(this)).ConsultarArticuloPorCodigoSoapAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioArticulos_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioArticulos_soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7208/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioArticulosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioArticulos_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioArticulosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioArticulos_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioArticulos_soap,
        }
    }
}
